# Generated by Django 5.0.4 on 2024-04-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_scope_is_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
