# Generated by Django 5.0.4 on 2024-04-19 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="sensor_id",
            new_name="sensor",
        ),
    ]
